//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _ExcellOn_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public int Id { get; set; }
        public string OrderDetail_DateCreate { get; set; }
        public string OrderDetail_DateEmploy { get; set; }
        public Nullable<int> OrderDetail_NumberOfDay { get; set; }
        public Nullable<int> OrderDetail_Status { get; set; }
        public Nullable<int> OrderDetail_NumberOfPeople { get; set; }
        public Nullable<int> ServiceId { get; set; }
        public Nullable<int> OrdersId { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Service Service { get; set; }
    }
}
